### ISSUE TITLE
Choix du style des pages

### ISSUE THREAD

**Issue by andinox** [andinox/Projet-Python-TSP#4]
Définir et appliquer le style visuel de l'interface utilisateur pour assurer une expérience agréable et intuitive. L'objectif est de créer un design épuré et fonctionnel, adapté aux utilisateurs non spécialisés dans les réseaux. Ce style doit faciliter la navigation, la lecture des résultats de diagnostic, et la reconnaissance des éléments critiques.
Objectifs

  - Développer une charte graphique cohérente et professionnelle, avec un style épuré et des couleurs douces.
  - Mettre en place des indicateurs visuels (code couleur) pour faciliter l'identification des erreurs dans les diagnostics.
  - Assurer une interface réactive et fluide, optimisée pour une utilisation web.

Objectif de l'issue : 
 - Trouver un framework css
 - Définir un code couleur

**Comment by andinox** [comment]
# Question ?
Bulma ou BootStrap ? Pour le framework css ?
[https://coolors.co/](url)

**Comment by dohaab14** [comment]
> # Question ?
> Bulma ou BootStrap ? Pour le framework css ? [https://coolors.co/](url) <-- pour le code couleur

Pour le début on commence avec Bulma et si besoin on se dirige sur BootStrap pour autres fonctionnalités

**Comment by dohaab14** [comment]
pour la palette de couleur: https://coolors.co/palette/086788-07a0c3-f0c808-fff1d0-dd1c1a

**Comment by Eclaizr** [comment]
Superbes vos palettes ! J'en ajoute une également : https://coolors.co/palette/1a535c-4ecdc4-f7fff7-ff6b6b-ffe66d

**Comment by andinox** [comment]
Pour les couleurs 

> pour la palette de couleur: https://coolors.co/palette/086788-07a0c3-f0c808-fff1d0-dd1c1a

J'aime bien ! Go prendre celle-là
